#!/bin/bash

file_input="result3.txt"
file_output="result5.txt"

prev_ppid="0"
art_sum="0"
count="0"
m="0"

while read line
do
	echo $line
	ppid=$(awk '{print $2}' <<< $line )
	art=$(awk '{print $3}' <<< $line )
	pid=$(awk '{print $1}'<<< $line )
	if [[ $prev_ppid == $ppid ]]
	then

		
		count=$(($count+1))
		m=$(($m+$art))
		echo line >> $file_output 
	else
		echo $count
		if [[ $count -ne "0" ]]
		then
			m=$(($m/$count))
		fi
		echo "Average_Sleeping_Children_of_PatientID="$prev_ppid" is "$m >> $file_output
		prev_ppid=$ppid
		count="0"
		m="0"
	
	fi



done < $file_input




