#!/bin/bash
echo "	Menu"
echo "Nano - 1	Vi - 2"
echo "Links - 3	Exit - 4"
read line
while [ "$line" != "4" ]
do
case "$line" in
"1")
exec "nano"
;;
"2")
exec "vi"
;;
"3")
exec "links"
;;
"4")
exit
;;
esac
read line
done
